---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-karpenter
  region: us-west-2
  version: '1.21'
managedNodeGroups:
  - instanceType: t3.medium
    amiFamily: AmazonLinux2
    name: my-karpenter-ng
    desiredCapacity: 1
    minSize: 1
    maxSize: 10
iam:
  withOIDC: true
